import { useState } from 'react'
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import toast from 'react-hot-toast'
import { useQuery } from '@tanstack/react-query'
import RequireRole from '../components/Auth/RequireRole.jsx'
import { getTimeseries, getFacilities } from '../api/client.js'

function ReportsDashboard() {
  const { data: facilitiesData } = useQuery({
    queryKey: ['facilities'],
    queryFn: () => getFacilities(),
    refetchInterval: 60000,
  })
  const facilities = facilitiesData?.facilities || []
  
  const [selectedFacility, setSelectedFacility] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)

  const handleGenerate = async () => {
    if (!selectedFacility) {
      toast.error('Please select a facility')
      return
    }

    const fac = facilities.find(f => f.id === selectedFacility)
    if (!fac) return

    setIsGenerating(true)
    const id = toast.loading('Generating Official Report...')

    try {
      const ts = await getTimeseries(fac.id, 30)
      
      const pdfDoc = await PDFDocument.create()
      const page = pdfDoc.addPage([600, 800])
      const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica)
      const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

      // Header
      page.drawText('MethaneX Regulatory Report', { x: 50, y: 750, size: 24, font: helveticaBold, color: rgb(0.1, 0.4, 0.8) })
      page.drawText(`Generated: ${new Date().toLocaleString()}`, { x: 50, y: 730, size: 10, font: helvetica, color: rgb(0.4, 0.4, 0.4) })
      
      page.drawLine({ start: { x: 50, y: 715 }, end: { x: 550, y: 715 }, thickness: 1, color: rgb(0.8, 0.8, 0.8) })

      // Facility Info
      page.drawText('Facility Information', { x: 50, y: 680, size: 16, font: helveticaBold, color: rgb(0, 0, 0) })
      
      const info = [
        ['Name:', fac.name],
        ['Type:', fac.type?.replace(/_/g, ' ')],
        ['Location:', `${fac.lat?.toFixed(4)}, ${fac.lon?.toFixed(4)} (${fac.country})`],
        ['Operator:', fac.operator || 'MethaneX'],
        ['Risk Score:', `${((fac.risk_score || 0) * 100).toFixed(1)}%`]
      ]

      let y = 650
      info.forEach(([label, value]) => {
        page.drawText(label, { x: 50, y, size: 12, font: helveticaBold })
        page.drawText(String(value || 'N/A'), { x: 150, y, size: 12, font: helvetica })
        y -= 25
      })

      // Emissions Data
      page.drawLine({ start: { x: 50, y: y - 10 }, end: { x: 550, y: y - 10 }, thickness: 1, color: rgb(0.8, 0.8, 0.8) })
      y -= 40
      
      page.drawText('Emissions Summary (Last 30 Days)', { x: 50, y, size: 16, font: helveticaBold, color: rgb(0, 0, 0) })
      y -= 30

      const avg = ts?.average_emission_kg_hr || fac.historical_emission_rate || 0
      page.drawText(`Latest Emission Rate: ${fac.historical_emission_rate} kg/hr`, { x: 50, y, size: 12, font: helveticaBold })
      
      const complianceStatus = avg > 100 ? 'NON-COMPLIANT (Super-Emitter)' : 'COMPLIANT'
      const complianceColor = avg > 100 ? rgb(0.8, 0.1, 0.1) : rgb(0.1, 0.6, 0.1)
      
      page.drawText(`Status: ${complianceStatus}`, { x: 300, y, size: 12, font: helveticaBold, color: complianceColor })

      // Draw Mini Chart
      y -= 40
      page.drawText('30-Day Emission Trend', { x: 50, y, size: 12, font: helveticaBold })
      y -= 20

      const chartX = 50
      const chartY = y - 150
      const chartW = 500
      const chartH = 150

      // Chart background
      page.drawRectangle({ x: chartX, y: chartY, width: chartW, height: chartH, color: rgb(0.95, 0.95, 0.95) })

      if (ts && ts.series && ts.series.length > 0) {
        const maxVal = Math.max(...ts.series.map(d => d.emission_rate_kg_hr), 100)
        const barW = chartW / ts.series.length
        
        ts.series.forEach((d, i) => {
          const barH = (d.emission_rate_kg_hr / maxVal) * chartH
          const color = d.emission_rate_kg_hr > 100 ? rgb(0.9, 0.2, 0.2) : rgb(0.2, 0.6, 0.9)
          page.drawRectangle({
            x: chartX + (i * barW) + 1,
            y: chartY,
            width: barW - 2,
            height: barH,
            color
          })
        })
      } else {
        page.drawText('No timeseries data available', { x: chartX + 180, y: chartY + 70, size: 10, font: helvetica, color: rgb(0.5, 0.5, 0.5) })
      }

      // Footer
      page.drawText('Generated by MethaneX Regulatory Compliance Engine', { x: 50, y: 50, size: 10, font: helvetica, color: rgb(0.5, 0.5, 0.5) })

      const pdfBytes = await pdfDoc.save()
      const blob = new Blob([pdfBytes], { type: 'application/pdf' })
      const url = URL.createObjectURL(blob)
      
      const link = document.createElement('a')
      link.href = url
      link.download = `MethaneX_Report_${fac.name.replace(/\s+/g, '_')}.pdf`
      link.click()
      URL.revokeObjectURL(url)

      toast.success('Report generated!', { id })
    } catch (err) {
      toast.error('Failed to generate report', { id })
    } finally {
      setIsGenerating(false)
    }
  }

  return (
    <div style={{ padding: '40px', maxWidth: '800px', margin: '0 auto' }}>
      <h1 style={{ fontSize: '28px', fontWeight: 800, marginBottom: '8px' }}>Regulatory Reports</h1>
      <p style={{ color: 'var(--text-secondary)', marginBottom: '32px' }}>
        Generate officially formatted PDF reports with timestamped, immutable audit trails.
      </p>

      <div className="glass" style={{ padding: '32px', borderRadius: '12px' }}>
        <h3 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '16px' }}>Select Facility for Report</h3>
        
        <select 
          className="input" 
          value={selectedFacility} 
          onChange={(e) => setSelectedFacility(e.target.value)}
          style={{ width: '100%', marginBottom: '24px', padding: '12px', fontSize: '16px' }}
        >
          <option value="">-- Choose a Facility --</option>
          {facilities.map(f => (
            <option key={f.id} value={f.id}>{f.name} ({f.country}) - {f.historical_emission_rate} kg/hr</option>
          ))}
        </select>

        <button 
          className="btn btn-primary" 
          onClick={handleGenerate} 
          disabled={!selectedFacility || isGenerating}
          style={{ width: '100%', padding: '16px', fontSize: '16px', justifyContent: 'center' }}
        >
          {isGenerating ? 'Generating PDF...' : '📄 Generate Official PDF Report'}
        </button>

        <div style={{ marginTop: '24px', padding: '16px', background: 'rgba(255, 68, 68, 0.1)', border: '1px solid rgba(255, 68, 68, 0.2)', borderRadius: '8px' }}>
          <div style={{ fontSize: '12px', color: '#ff4444', fontWeight: 700, marginBottom: '4px' }}>REGULATORY NOTICE</div>
          <p style={{ fontSize: '13px', color: 'var(--text-secondary)' }}>
            Reports generated via this tool are watermarked and timestamped for regulatory submission. Any detected super-emitter events (&gt;100 kg/hr) will be automatically flagged as NON-COMPLIANT.
          </p>
        </div>
      </div>
    </div>
  )
}

export default function ReportsPage() {
  return (
    <RequireRole role="regulator">
      <ReportsDashboard />
    </RequireRole>
  )
}
